# fly.toml app configuration file generated for 60-buttons-api on 2023-12-09T07:47:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "60-buttons-api"
primary_region = "sin"

[env]
  Cors__Origins__0="https://buttons.qinguan.me"
  
[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  
[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true
 
[[services.ports]]
  handlers = ["tls", "http"]
  port = 443
 
[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/healthz"
  protocol = "https"
  timeout = "2s"
  tls_skip_verify = false
  [services.http_checks.headers]