# fly.toml app configuration file generated for 60-buttons-api on 2023-12-09T07:47:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "60-buttons-api"
primary_region = "sin"

[mounts]
  source="60_buttons_api_data"
  destination="/data"

[env]
  Cors__Origins__0="https://buttons.qinguan.me"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
